name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Configure github
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: npm install, build, and test
        run: |
          npm install
          npx hexo clean
          npx hexo generate
          npx hexo deploy
        env:
          CI: true
          GITHUB_TOKEN: ${{secrets.publish_token}}
