name: Deploy site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt remove cmdtest
          sudo apt update && sudo apt install --no-install-recommends yarn
      - name: Setup github
        run: |
          mkdir -p ~/.ssh/
          echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'wangpin34'
          git config --global user.email 'wangpin34@users.noreply.github.com'
        env:
          GH_ACTION_DEPLOY_KEY: ${{secrets.GH_ACTION_DEPLOY_KEY}}

      - name: Setup theme
        working-directory: ./themes
        run: |
          git clone git@github.com:wangpin34/hexo-theme-remind hexo-theme-remind

      - name: Build
        run: |
          yarn
          npx hexo generate

      - name: Deploy
        run: |
          npx hexo deploy
